With the changes to support automatic forward declarations of type names, gccgo no longer reports redefinition errors for :=, because it no longer knows at parse time whether the type has changed.  Adjust this test to not match "redefinition", and to instead match gccgo's current output.
declbad.go:19:3: error: variables redeclared but no variable is new
declbad.go:34:3: error: variables redeclared but no variable is new
declbad.go:39:3: error: variables redeclared but no variable is new
declbad.go:44:3: error: variables redeclared but no variable is new
declbad.go:49:3: error: variables redeclared but no variable is new
declbad.go:24:3: error: incompatible types in assignment
declbad.go:29:3: error: incompatible types in assignment
declbad.go:39:3: error: incompatible types in assignment

R=rsc
DELTA=10  (0 added, 0 deleted, 10 changed)
OCL=33537
CL=33539